name: PlayerWarps
authors: [Revivalo]
description: Warps created by players for players
version: ${project.version}

main: dev.revivalo.playerwarps.PlayerWarpsPlugin
api-version: 1.13
depend:
  - Vault # https://www.spigotmc.org/resources/vault.34315/
softdepend:
  - Multiverse-Core # https://www.spigotmc.org/resources/multiverse-core.390/
  - Multiworld # https://www.spigotmc.org/resources/multiworld.4598/
  - DiscordSRV # https://www.spigotmc.org/resources/discordsrv.18494/
  - ChatControlRed
  - ChatControl
  - Essentials
  - dynmap # https://www.spigotmc.org/resources/dynmap%C2%AE.274/
  - BlueMap # https://www.spigotmc.org/resources/bluemap.83557/
  - BentoBox # https://www.spigotmc.org/resources/bentobox-bskyblock-acidisland-skygrid-caveblock-aoneblock-boxed.73261/
  - SuperiorSkyblock2 # https://www.spigotmc.org/resources/%E2%9A%A1%EF%B8%8F-superiorskyblock2-%E2%9A%A1%EF%B8%8F-the-best-core-on-market-%E2%9A%A1%EF%B8%8F-1-21-3-support.87411/
  - WorldGuard # https://dev.bukkit.org/projects/worldguard/files
  - GriefPrevention # https://www.spigotmc.org/resources/griefprevention.1884/
  - Residence # https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-21.11480/
  - Territory # https://www.spigotmc.org/resources/%E2%AD%90%EF%B8%8Fterritory-new-land-claiming-plugin.121522/

commands:
  pwarp:
    description: Main command for PlayerWarps plugin
    usage: /<command>
    aliases: [pw, playerwarps]

permissions:
  playerwarps.use:
    description: Allows you to teleport to public warps
    default: true
  playerwarps.create:
    description: Allows you to create a warp
    default: true
  playerwarps.settings:
    description: Allows you to setup the warp
    default: true